version: '3.9'
services:
  weatherapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTP_PORTS=8081
    container_name: weatherapi
    image: weatherapi
    build:
      dockerfile: web/Dockerfile
    restart: always
    ports:
      - "8081:8081"