version: '3.7'
name: weathersql
services:
  mssql:
    container_name: sql-server-2022-cu10-ubuntu
    image: mcr.microsoft.com/mssql/server:2022-CU10-ubuntu-22.04
    ports:
      - 1433:1433
    volumes:
      - sql-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
volumes:
    sql-data: